import React from 'react'
import { Link } from 'react-router-dom'
const TandC = () => {
  return (
    <>
      {/* Top breadcrumb */}
      <div className="text-sm p-4 sm:p-5" style={{ backgroundColor: "#f0f3fc" }}>
        <div className="max-w-6xl mx-auto text-center md:text-left">
          <Link to="/" className="font-semibold text-purple-700">
            Home
          </Link>{" "}
          &gt; <span className='font-bold'>Terms & Conditions</span>
        </div>
      </div>



      <div className="bg-white text-gray-800 p-4 sm:p-8 md:p-12 max-w-5xl mx-auto">
        {/* Main Title */}
        <h1 className="text-3xl sm:text-5xl font-bold text-center italic mb-8 text-purple-800">
          TERMS AND CONDITIONS
        </h1>

        {/* Section A */}
        <h2 className="text-xl sm:text-4xl font-bold text-center italic text-purple-800 mb-4">
          A. GENERAL
        </h2>
        <ul className="list-decimal list-inside space-y-2 text-sm sm:text-lg ">
          <li>
            These are the Terms and Conditions of Use (‘Terms’) which form a legal and binding agreement amongst Us or its affiliates or subsidiaries (referred to as the ‘Us’, ‘We’ or ‘Our’) and any person (‘You’/ ‘Your’/ ‘User’) accessing:
            <ul className="list-disc list-inside ml-6">
              <li>Our website – <span >www.zupee.com</span> (‘<strong>Website</strong>’) and the Zupee mobile application (‘<strong>App</strong>’) including any subdomains of the Website, mobile sites, apps, APIs, widgets (hereinafter collectively referred as ‘<strong>Platform’</strong>), and/or;</li>
              <li>any data, information, text, graphics, video, sound, pictures, and any other materials appearing, sent, uploaded, communicated, transmitted, or otherwise made available via the Platform (jointly referred to as the ‘<strong>Content</strong>’) for participating in various contests and games hosted on the Platform (<strong>‘Services</strong>’/ ‘<strong>Games</strong>’).</li>

            </ul>
          </li>
          <li>
            Such User (as described above) shall be bound by these Terms, (Privacy Policy) and all other rules, regulations, and terms of use (including Privacy Policy) referred to herein or provided by Us in relation to any Services
          </li>
          <li>
            This document is an electronic record in terms of the Information Technology Act, 2000 and rules there under as applicable and various other statutes. This electronic record is generated by a computer system and does not require any physical or digital signatures.
          </li>


          <li>We reserve the right to amend, modify, update, terminate, supplement, or otherwise amend all or any of the Terms, Privacy Policy, rules, or regulations on the Platform at any time by publishing new Terms. We may, at its sole discretion, also notify the User of any change or modification in these Terms, Privacy Policy, rules, regulations, and terms of use referred to herein or provided by Us, by way of sending an email to the User’s registered email address or posting notifications in the User accounts. The User may then exercise the options provided in such an email or notification to indicate non-acceptance of the modified Terms, rules, regulations, and terms of use referred to herein or provided by Us. If such options to indicate non-acceptance are not exercised by the User within the period prescribed in the email or notification, the User will be deemed to have accepted the modified Terms, rules, regulations, and terms of use referred to herein or provided by Us.</li>
          <li>These terms are made available via the app store or platform that you download our Games from (such as the iOS App Store, Google Play Store, Amazon App Store, Windows Phone Store </li>
          <li>You acknowledge and agree that by using, or otherwise accessing Our Platform and Services, you agree to be bound by these Terms and our . You acknowledge that we provide use and access to our Platform and Services to you, subject to these Terms. You agree and acknowledge that you have completely read and understood these Terms and the Privacy Policy, incorporated herein by reference, as amended from time to time. You agree, covenant, and undertake to be bound by the specific rules and regulations of each of the Games as applicable.</li>
          <li>If the User does not accept the modified Terms, rules, regulations, and terms of use referred to herein or provided by Us, we reserve the right to deny access to the Platform and Services to the User. If the User does not accept the modified Privacy Policy, we reserve the right to deny access to the Platform and Services to the User to the extent such modified terms of the Privacy Policy are required to provide access to the Platform and Services.</li>
          <li>Participation in any Games or contest on Our Platform or viewing of certain Content may be subject to further terms and conditions as may be notified by us from time to time on the Website or otherwise. You should ensure that you have read, understood, and agree to abide by the rules and regulations of the Games, contests, and tournaments available through Our Platform.</li>
          <li>We may, at its sole and absolute discretion: </li>
          <ol className="list-disc ml-6 list-inside space-y-2 text-sm sm:text-lg">
            <li>Move or remove any Content that is available or posted by a User on the Platform.</li>
            <li>Establish general practices and limits concerning the use of the Platform and modify these practices, limits, and thresholds at its discretion, from time to time, and such changes shall be notified and/or included within updated Terms as deemed fit by Us.</li>
            <li>Assign its rights and liabilities to all User accounts hereunder to any entity (post such assignment, intimation of such assignment shall be sent to all Users to their registered email addresses).</li>
          </ol>
          <li>Your use of information on our Platform including results, fixture lists, statistics, data, and news posted on our Platform is at your own risk. Other than as expressly set out in these Terms and to the extent permitted by law, we make no warranty as to the accuracy or reliability of the information contained on our Platform or in our publications (including, but not limited to, any Content or information generated on our Platform by or on behalf of us, and any third-party content on our Platform). We and our related entities, directors, officers, and agents disclaim all liability and responsibility for any loss or damage (whether direct or indirect) that may be suffered by any recipient through relying on anything contained in or omitted from our Platform or publications.</li>
          <li>You hereby unconditionally and irrevocably, expressly agree to the transfer of your personal data and information (including sensitive data) to Us and to such third parties who we contract with to provide you with the Services.</li>
        </ul>

        <hr className='mt-10' />

        {/* Section B */}
        <h2 className="text-xl sm:text-4xl font-bold text-center italic text-purple-800 mt-10 mb-4">
          B. DESCRIPTION OF SERVICES OFFERED
        </h2>
        <ul className="list-decimal list-inside space-y-2 text-sm sm:text-lg">
          <li>
            Subject to the Users compliance with these Terms, We give Users a personal, royalty-free, non-assignable, non-sublicensable, non-transferable, non-exclusive, and revocable limited right to access and use the Platform that is provided as part of the Services. This right is for the sole purpose of enabling the own personal private use from Users to play Games as hosted on the Platform, in the manner prescribed under these Terms and not for any commercial purposes and only until the User is bound by these Terms.
          </li>
          <li>
            The Services may change or be modified from time to time without prior notice or communication. We reserve the right to change, modify or delete the Platform or Services, information, and Terms listed thereon at any time without prior notice.
          </li>
          <li>
            The Services may include advertisements, which may be targeted to the Content or information on the Services, queries made through the Services, or any other information. The types and extent of advertising by Us on the Services are subject to change.
          </li>
          <li>When access Games are included in the Services, the specific rules, scoring, controls, and guidelines for each game can be found within the game itself. The Users agree to and shall comply with such rules, scoring, controls, and guidelines </li>
          <li>Any charges levied on Users for accessing the Services, including but not limited to internet connection and/or mobile or data charges are solely the responsibility of such Users.</li>
          <li>The Service imposes certain restrictions on its usage, which are outlined below:</li>
          <ul className='list-disc list-inside ml-8 space-y-2 text-sm sm:text-lg'>
            <li>You must not create an Account or access the Service if you are below the age specified by platforms like Google Play Store, App Store, or Instant Games (Facebook).</li><li>It is your responsibility to monitor your Account and prevent minors under the age of 18 from accessing it. You accept full responsibility for any unauthorized use of the Service by minors using your Account, including the use of payment methods.</li><li>You are not permitted to have more than one Account per platform or social networking service (SNS) simultaneously. Additionally, you must not create an Account using false information or on behalf of someone else.</li><li>Individuals who are convicted sex offenders are prohibited from creating an Account or using the Service.</li><li>If you have been previously removed or banned by us from playing any of our games, you are not allowed to create a new Account or use the Service.</li><li>Your Account should only be used for non-commercial purposes.</li><li>You are prohibited from using your Account to advertise, solicit, or send any commercial advertisements, including chain letters, junk emails, or repetitive messages (spam) to anyone.</li><li>You must not use your Account to engage in any illegal activities.</li><li>Without our written permission, you are not allowed to sublicense, rent, lease, sell, trade, gift, bequeath, or transfer your Account or any Virtual Items associated with your Account to anyone.</li><li>You are not permitted to access or use an Account or Virtual Items that have been transferred from the original Account creator without our permission.</li><li>If you access the Service through a social networking service (SNS), you must also comply with the SNS's terms of service/use in addition to these Terms of Service.</li>
          </ul>
          <li>IN THE GAMES, AS INTRODUCED FROM TIME TO TIME, YOU MAY WIN OR LOSE VIRTUAL CHIPS. THESE VIRTUAL CHIPS HAVE NO REAL CASH VALUE AND CANNOT BE ENCASHED FOR ANY PRIZE, WINNINGS REWARD, CONSIDERATION, PROFIT, OR GAIN EQUIVALENT TO ANY REAL MONEY VALUE WHATSOEVER. PARTICIPATION IN THESE GAMES IS COMPLETELY FREE. IF YOU SPEND ALL YOUR FREE VIRTUAL CHIPS, YOU CAN PURCHASE MORE VIRTUAL CHIPS TO PLAY BY MAKING PAYMENTS INSIDE THE GAME ITSELF. THESE GAMES DO NOT OFFER REAL MONEY GAMBLING, WAGERING OR BETTING OR ANY OPPORTUNITY TO WIN REAL MONEY OR PRIZES.</li>
          <li>Notwithstanding anything contained in these Term or any other policies, if You have never made a deposit into Your user wallet (excluding any credits to your play money wallet arising out of any transfer you may have made from your winnings wallet to your play money wallet) and if You have neither participated in a Game nor made a withdrawal, for a period of ninety (90) consecutive days, then any amounts standing to the credit of your winnings wallet and/or play money wallet (including any credits to your play money wallet arising out of any transfer you may have made from your winnings wallet to your play money wallet) shall be forfeited by Us immediately on 91st (ninety-first) day. Upon such forfeiture, You shall have no further claim over these amounts, and We shall bear no liability in this regard. </li>
        </ul>
        <hr className='mt-10' />

        {/* Section C */}
        <h2 className="text-xl sm:text-4xl font-bold text-center italic text-purple-800 mt-10 mb-4">
          C. USER REGISTRATION
        </h2>
        <ul className="list-decimal list-inside space-y-2 text-sm sm:text-lg">
          <li>
            In order to access the Website or fully utilize the Platform offered by Us, a User is required to register on the Platform. You are not authorised to access any of our Platform, until you have been granted an Account (defined below).

          </li>
          <li>
            If you wish to become a registered User, you will need to create an account (‘<strong>Account</strong>’) on our Platform, have a valid account on the social networking service (‘SNS’) through which you connect to the Service, if any, or have an account with the applications provider for your mobile device. Each User is only permitted to open one Account. We reserve the right to terminate or suspend any duplicate accounts.
          </li>
          <li>
            In order to create or update an Account, We may require you to register by completing a form and providing certain details, which may include your name, birth date, e-mail address, and in some cases, payment information. This information will be held and used in accordance with Our Privacy Policy and relevant “just-in-time” notices, if any, provided at the point of information collection or use. You agree that you will supply accurate and complete information to Us, and that you will update the information promptly after it changes.
          </li>
          <li>You understand that your user ID number, name, and picture on our websites/applications will be publicly available and that search engines may index your name and profile photo.</li>
          <li>You can also register or log in through your Google e-mail address or using a guest log-in. Permission to open the Account shall be determined by Us or its representatives, at their sole discretion. We may refuse to grant an application for an Account made by any person without giving a reason for such refusal. You agree and acknowledge that Our decision in this regard shall be final.</li>
          <li>Your information, and the contents of all of your online communications (including without limitation chat text, voice communications, IP addresses and your personal information) may be accessed and monitored as necessary to provide the Service and may be disclosed: (i) when We have a good faith belief that We are required to disclose the information in response to legal process (for example, a court order, search warrant or subpoena); (ii) to satisfy any applicable laws or regulations (iii) where We believe that the Service is being used in the commission of a crime, including to report such criminal activity or to exchange information with other companies and organizations for the purposes of fraud protection and credit risk reduction; (iv) when We have a good faith belief that there is an emergency that poses a threat to the health and/or safety of you, another person or the public generally; and (v) in order to protect Our rights or property, including to enforce our Terms of Service. By entering into these Terms of Service, you hereby provide your irrevocable consent to such monitoring, access, and disclosure.</li>
        </ul>
        <hr className='mt-10' />

        {/* Section D */}
        <h2 className="text-xl sm:text-4xl font-bold text-center italic text-purple-800 mt-10 mb-4">
          D. ELIGIBILITY
        </h2>
        <ul className="list-decimal list-inside space-y-2 text-sm sm:text-lg">
          <li>
            You warrant that you are not prohibited from receiving products of Indian origin, including services or software.
          </li>
          <li>You must be over 18 years of age to access and/or use our Platform and create an Account with us. By agreeing to these Terms, you represent and warrant to us that: (a) you are at least 18 years old; (b) you have not previously been suspended or blocked from using the Platform; and (c) your registration and your use of the Platform is in compliance with any and all applicable laws and regulations.</li>
          <li>
            We reserve the right to request proof of identity at any stage to verify that minors are not using the Platform and we may exclude a person from accessing or using the Platform if proof of identity is not provided or if We suspect that a person is under the age of 18 years.
          </li>
          <li>Parents and guardians should monitor their children’s / ward’s online activities and consider using parental control tools available from online services that help provide a child an amicable online environment. These tools can also prevent children from disclosing any personal information without parental permission. </li>
          <li>You agree to provide true, accurate, current, and complete information at the time of registration and at all other times (as required by Us). You agree to update and keep updated all information provided for the purposes of registration. You undertake and agree that all information provided by you from time to time is true, accurate, current, and complete to your personal knowledge.</li>
        </ul>
        <hr className='mt-10' />

        {/* Section E */}
        <h2 className="text-xl sm:text-4xl font-bold text-center italic text-purple-800 mt-10 mb-4">
          E. CREATION OF ACCOUNT AND USE OF THE PLATFORM
        </h2>
        <ul className="list-decimal list-inside space-y-2 text-sm sm:text-lg">
          <li> Upon grant of the Account by us, your Account will be created, and you will be able to use our Platform, access the
            Service(s) and play the Game(s) hosted by us. You agree and acknowledge that such an Account can be terminated by us
            by giving notice to you, for any reason deemed fit by Us in Our sole discretion.</li>
          <li> You represent and warrant to us that, throughout the course of your usage of our Platform
            , you will not permit other persons to access or use your Account. If you permit other persons to
            access or use your Account, you do so at your own sole risk as to any consequences. You further agree
            and accept that you shall not access or use the Platform through the Account of another User.</li>
          <li> By accepting these terms and conditions upon registration, you give consent to Us to disclose
            your personal information provided to us to a third-party agency to assist in verifying your identity.
            The third-party agency may prepare and provide Us with such an assessment and may use your personal information including the
            names, residential addresses and dates of birth, financial information etc. for the purposes of preparing such
            an assessment. Please refer to our Privacy Policy in this regard.</li>
          <li> You acknowledge that your participation in any Game(s) available on the Platform
            is purely voluntary and at your sole discretion and risk.</li>
          <li> We verify User(s) location by logging of IP address for location mapping and User
            (s) hereby consents for collection of aforementioned information. We reserve the right to delete/remove
            such Account(s) without any notice and in its sole and absolute discretion.</li>
        </ul>
        <hr className='mt-10' />

        {/* Section F */}
        <h2 className="text-xl sm:text-4xl font-bold text-center italic text-purple-800 mt-10 mb-4">
          F. THIRD PARTY ADVERTISEMENTS
        </h2>

        <ul className="list-decimal list-inside space-y-2 text-sm sm:text-lg">
          <li>
            You acknowledge that the Service and Our games may display advertisements by Us or third parties as explained in Our Privacy Policy..
          </li>
          <li>
            The Service may contain links to third-party websites or vendors that may offer you a promotional deal in exchange for optional components of the Service or upgrades (such as in-game currency). Any charges or obligations you incur in your interactions with these third parties are solely your responsibility. We do not guarantee or warrant the content, goods, and/or services provided by any third party, even if they are linked to from our Service, and We will not be held liable for any claims related to such third-party content, goods, and/or services. These linked sites are not controlled by Us and We may gather data or request personal information from you. We are not responsible for the content, business practices, or privacy policies of these sites, nor for the collection, use, or disclosure of any information they may gather. Additionally, the inclusion of any link does not imply endorsement by Us of the linked sites.
          </li>
        </ul>
        <hr className='mt-10' />

        {/* Section G */}
        <h2 className="text-xl sm:text-4xl font-bold text-center italic text-purple-800 mt-10 mb-4">
          G. SECURITY
        </h2>
        <ul className="list-decimal list-inside space-y-2 text-sm sm:text-lg">
          <li> Access to your Account and to add, delete or modify any Content on your Account is password/OTP protected.</li>
          <li> We are not liable for any loss, damages or expenses of any kind incurred or suffered by you arising from or in connection with any failure, delay or interruption, interception, interference, in transmitting passwords/OTPs due to any failure of the mobile service network or any other circumstance beyond our reasonable control.</li>
          <li> You agree that you will not disclose your password / OTP to anyone or allow any other person to access or use your Account. We are not responsible if your Account is accessed or opened by other persons using your password. You shall be held solely responsible and liable for all your activities on the Platform made from your Account.</li>
          <li> You understand that it is your obligation to protect the information you have provided on the Platform including, but not limited to usernames, passwords, email addresses, contact details, bank account information etc. You explicitly understand and agree that we will not incur any liability for information provided by you to anyone which may result in your Account on the Platform being exposed or misused by any other person or any other harm or loss being suffered by you.</li>
          <li> Provided that We have not engaged in fraud or gross negligence, We will not be liable to a User for any authorised transaction which has been executed through the Platform as a result of:  fraud committed by any User using User’s access credentials before the User has notified Us in writing of the loss or theft or such access credentials, as a result of which We have been unable to take any action to disable the access credentials;
            <ol className='list-disc list-inside ml-8 space-y-2 text-sm sm:text-lg'>
              <li>fraud committed by any User using User’s access credentials before the User has notified Us in writing of the loss or theft or such access credentials, as a result of which We have been unable to take any action to disable the access credentials;</li>
              <li> fraud committed by third parties against Users which may not be preventable by, or occur despite the security systems of the Platform;</li>
              <li>a voluntary action or transaction initiated suo motu by any User at the behest of another User, which is not initiated by Us for the transfer of funds, credit, or stored value to another User;</li>
              <li>the security, accuracy, legality, appropriateness or any other aspect of the Content or function of any third party’s products or services on our Platform</li>
            </ol>

          </li><li> Please also contact us immediately if your mobile or computer device through which you access the Platform has been lost, stolen, or compromised in any way or someone has used or may use your mobile or computer device or credentials without your authorisation or if you become aware of any unauthorised use of your Account.</li>
          <li> You should only transact with a third-party product or service that you know.</li>
          <li> Please note that we can terminate or suspend your Account and all associated accounts, institute fraud prevention measures such as access restrictions, transaction velocity restrictions etc., without prior notice to prevent unauthorised use of our Platform. You must co-operate with us in any investigation and use any fraud prevention measures we prescribe, and you agree that we will not be liable to you or any third party for any block, suspension, cancellations, or termination of your use of an Account owing to such measures.</li>
          <li> You are hereby informed that any and all information associated with any fraudulent transaction may be shared by Us (with or without demand) with the appropriate government body, law enforcement body, or any agency thereof, for the purpose of verification of the identity of User, or for prevention, detection, investigation, prosecution, and punishment.</li>
        </ul>


        <hr className='mt-10' />


        {/* Section H */}
        <h2 className="text-xl sm:text-4xl font-bold text-center italic text-purple-800 mt-10 mb-4">
          H. USER CONDUCT
        </h2>
        <ul className="list-decimal list-inside space-y-2 text-sm sm:text-lg">
          <li>In accessing or using our Platform you agree that you will not: </li>
          <ol className='list-disc list-inside ml-8 space-y-2 text-sm sm:text-lg'>
            <li>use any automated device, software, process or means to access, retrieve, scrape, or index our Platform or any Content thereon without our express prior written consent;</li><li>use any device, software, process or means to interfere or attempt to interfere with the proper working of our Platform;</li><li>undertake any action that will impose a burden or make excessive traffic demands on our infrastructure that we deem, in our sole discretion, to be unreasonable or disproportionate site usage;</li><li>use or index any Content or data on our Platform for purposes of competing with us in any manner that we have not specifically authorised; transmit spam, chain letters, games, junk email, surveys, or other mass messaging, whether commercial in nature or not;</li><li>use our Platform or any Content there from in any manner which is, in our sole discretion, not reasonable and / or not for the purpose it is made available;</li><li>violate the rights of any person, including copyright, trade secret, privacy right, or any other intellectual property or proprietary right;</li><li>pose as any person or entity or attempt to solicit money, passwords, or personal information from any person;</li><li>act in violation of any Terms of using our Platform;</li><li>reproduce, republish, retransmit, modify, adapt, distribute, translate, create derivative works or adaptations of, publicly display, sell, trade, or in any way exploit our Platform or any Content thereon, except as expressly authorised by us; or</li><li>transmit or attempt to transmit any computer viruses, worms, defects, Trojan horses, or other items of a destructive nature.</li>
          </ol>
          <li>If you choose to submit any content by way of question on the Platform, you hereby warrant that no Content shall:</li>
          <ol className='list-disc list-inside ml-8 space-y-2 text-sm sm:text-lg'>
            <li>be considered to be, unlawful, threatening, abusive, bigoted, hateful, libelous, tortious, blasphemous, false or misleading, discriminatory, defamatory, obscene, vulgar, offensive, excessively violent, invasive of another’ privacy, publicity, contract or other rights, pornographic or inclusive of nudity, paedophilic, profane, sexually explicit, indecent, racially, ethnically objectionable, disparaging, relating or encouraging money laundering, or otherwise unlawful in any manner whatsoever;</li><li>constitute, advocate, or encourage conduct that would constitute or give rise to a criminal offense, civil liability, or other violation of any local, state, national or international law;</li><li>constitute or contains false or misleading indications of origin or statements of fact;</li><li>belongs to another person and to which you do not have any right to, or infringe the Our intellectual property rights (whether registered or unregistered) or any third party;</li><li>contain any information, software or other material of a commercial nature or is patently false or untrue;</li><li>contain advertising, promotions, or commercial solicitations of any kind;</li><li>harass or harm another person;</li><li>exploit or endanger a minor;</li><li>impersonate or attempt to impersonate any person or entity or mislead or attempt to mislead another person regarding your identity;</li><li>threaten the unity, integrity, defence, security or sovereignty of the territory, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation.</li>
          </ol>
          <li>
            As it concerns the content uploaded by you, without prejudice to your obligation to otherwise comply with applicable laws during the course of using the Platform, you agree to hereby comply with any and all applicable laws, as well as any other rules and restrictions that may be set forth herein or on the Platform. We may not be held responsible for any content posted or contributed by Users on the Platform.
          </li>
          <li>The Users admit that they may be exposed to Content posted by other Users which they may find offensive, obnoxious, or indecent and that we may not be able to prevent such Content from being posted. Such Content should be brought to our notice. We shall act upon the information as it deems acceptable. The decision taken by Our management in this regard shall be final and binding on the User and you specifically agree that we shall not incur any liability under any circumstance whatsoever regarding the same.
            <li>We reserve the right to prevent unauthorised access to or use of our Platform, including, but not limited to, instituting technological barriers, or reporting your conduct to any person or entity.</li>
            <li>In the event, we have reasonable grounds to believe that your activities include any of the acts specified above, we may initiate appropriate legal action against you as well as notify the relevant regulatory or law enforcement authorities where appropriate in addition to any other available remedies under law or equity, apart from restricting or suspending or terminating your use of the Platform.</li></li>
          <li>You shall not purchase, sell, assign, trade, rent, loan, lease, license, grant a security interest in, or transfer your User Account, any content, currency, points, standings, rankings, ratings, or any other attributes appearing in, originating from, or associated with the Platform.</li>
          <li>Users agree to abide by these Terms and all other rules, regulations, and terms of use of the Platform. In the event User does not abide by these Terms and all other rules, regulations, and terms of use, We may, in our sole and absolute discretion, take necessary remedial action, including but not limited to:</li>
          <ol className='list-disc list-inside ml-8 space-y-2 text-sm sm:text-lg'><li>restricting, suspending, or terminating any User’s access to all or any part of Services;</li><li>deactivating or deleting a User’s Account and all related information and files on the Account; or</li><li>refraining from awarding any prize(s) or withholding access to such infringing User.</li></ol>
          <li>Users agree to ensure that they can receive all communication from Us by marking e-mails or push notifications. We will not be held liable if any e-mail/push notification remains unread by a User as a result of such e-mail getting delivered to the User’s junk or spam folder or user not receiving push notification If a User chooses a username that, in Our considered opinion is obscene, indecent, abusive or that might subject Us to public disparagement or scorn, We reserve the right, without prior notice to the User, to change the User’s username and inform the User, or delete such username and posts from Platform, deny such User access to Platform, or any combination of these options.</li>
          <li>Unauthorized access to Platform is a breach of these Terms, and a violation of the law. Users agree not to access the Platform by any means other than through the interface that is provided by Us for use in accessing Platform. Users agree not to use any automated means, including, without limitation, agents, robots, scripts, or spiders, to access, monitor, or copy any part of our sites, except those automated means that we have approved in advance and in writing.</li>
          <li>The use of the Platform is subject to existing laws and legal processes. Nothing contained in these Terms shall limit Our right to comply with governmental, court, and law-enforcement requests or requirements relating to User’s use of the Platform.</li>
          <li>We may not be held responsible for any content contributed by Users on the Platform.</li>
          <li>You will not use the Service(s) or any content provided by Us, or in connection with, or in any manner whatsoever, that relates to, or encourages or promotes, the activity of money laundering, gambling, betting, wagering or is otherwise unlawful or illegal in any manner whatsoever, under any Applicable Law. The Service(s) provided by Us are intended for entertainment purposes only and they do not, in any way, promote any form of gambling, wagering, or betting. We are not, and shall not be held to be responsible, directly, or indirectly, for any form of betting, wagering, or gambling acts/ activities that may take place outside these Terms as provided herein and hereby expressly disclaims any and all liability in connection therewith.</li>
          <li>We reserve the right to deny its Platform/ Services to any User in Our sole and absolute discretion. Such denial would automatically disqualify a User from playing any Games hosted on the Platform.</li>
          <li>The User represents and warrants that the documents provided during the verification process are true copies of the original documents to which they relate.</li>
          <li>Users are required to provide proper and complete details at the time of registration. We shall not be responsible for communications errors, commissions or omissions including those of the Users due to which the results may not be communicated to the Winner.</li>

        </ul>


        <hr className='mt-10' />






        {/* Section I */}
        <h2 className="text-xl sm:text-4xl font-bold text-center italic text-purple-800 mt-10 mb-4">
          I. Microseries
        </h2>
        <ul className="list-decimal list-inside space-y-2 text-sm sm:text-lg">
          <li>By accessing, downloading, installing, registering on, or using the Zupee Platform, including any of its applications, products, micro-series, or services, You acknowledge that You have read, understood, and agreed to be bound by these Terms, as well as the Privacy Policy and any other guidelines, rules, or supplemental terms published by Zupee from time to time.</li>
          <li>“Content” shall mean and include all material made available on or through the Platform, whether created, owned, or licensed by Zupee, its affiliates, partners, or uploaded by Users. This includes, without limitation, text, graphics, photographs, illustrations, icons, audio files, sound recordings, dialogues, gameplay clips, video recordings, animations, interactive features, guides, tutorials, and promotional material.</li>
          <li>Subject to compliance with these Terms, Zupee grants Users a limited, revocable, non-exclusive, non-transferable, and non-sublicensable license to access and use the Content solely for lawful, personal, and non-commercial purposes. Except as expressly permitted, Users shall not copy, reproduce, distribute, modify, adapt, translate, create derivative works from, publicly display, perform, or exploit any Content in any manner without the prior written consent of Zupee or the relevant rights holder. </li>
          <li>Users shall not employ any automated systems, including bots, crawlers, or scrapers, to access, harvest, or manipulate the Content. Reverse engineering, decompiling, tampering with, or attempting to extract source code from the Platform is strictly prohibited. Commercial exploitation of Content, including monetization of tournaments, unauthorized advertisements, sponsorships, or sale of access to contests, is not permitted.</li>
          <li>Users acknowledge that certain Content displayed on the Platform may be contributed or owned by third parties, including licensors, advertisers, and “Associated Brands.” All intellectual property rights in such Content remain vested with the respective owners, and Users shall not acquire any rights, title, or interest in the same. Zupee reserves the right to review, monitor, filter, or remove Content at its discretion, including where such Content violates applicable law, infringes intellectual property rights, or breaches these Terms.</li>
          <li>User Obligations and Lawful Use: As a condition of access to and use of the Platform, Users agree to comply with all applicable laws, rules, and regulations of India, as well as these Terms. Users shall not use the Platform for any unlawful, abusive, or fraudulent purposes, nor in any manner that could damage, disable, impair, or interfere with the functioning, security, or integrity of the Platform or the experience of other Users.</li>
          <li>Without limiting the generality of the foregoing, Users expressly agree not to:</li>


          <ol className='list-disc list-inside ml-8 space-y-2 text-sm sm:text-lg'>
            <li>
              Create, upload, publish, or distribute any content that is obscene, offensive, defamatory, derogatory, inflammatory, hateful, pornographic, abusive, unlawful, or otherwise objectionable.</li>
            <li>Misrepresent identity, impersonate another individual, misstate age, or provide false, misleading, or incomplete information at the time of registration or during the course of using the Platform.</li>
            <li>Employ automated programs, bots, scripts, or similar mechanisms to manipulate gameplay, score, rankings, or outcomes of contests.</li>
            <li>Engage in spamming, phishing, solicitation, harassment, stalking, or intimidation of other Users.</li>
            <li>Use the Platform to promote, advertise, or conduct unauthorized commercial activities, including the distribution of promotional codes, links, or affiliate offers not approved by Zupee.</li>
            <li>Circumvent, disable, or otherwise interfere with security-related features, anti-cheat mechanisms, or usage monitoring systems deployed on the Platform.</li>
            <li>Collect, harvest, or misuse personal data or other information belonging to Zupee or other Users without lawful authorization.</li>
            <li>Participate in collusion, cheating, or any activity that provides an unfair competitive advantage or undermines the integrity of the contests hosted on the Platform.</li>
          </ol>

          <li>Zupee reserves the right to investigate suspected violations of these obligations and to take such action as may be deemed appropriate, including but not limited to suspension or termination of User accounts, forfeiture of winnings, legal action, and reporting to law enforcement authorities.</li>
          <li>All rights, title, and interest in and to the Platform, including but not limited to software, source code, design, interface, layout, visual elements, databases, algorithms, features, and all Content made available by Zupee, are and shall remain the exclusive property of Zupee or its licensors. These are protected under applicable intellectual property laws, including copyright, trademark, design, and database protection laws.</li>
          <li>The names “Zupee,” “Zupee Free,” logos, symbols, graphics, mascots, slogans, product names, and any related trademarks or service marks (collectively, “Zupee Marks”) are the sole property of Zupee and are protected under the Trade Marks Act, 1999, and other applicable laws. Unauthorized use of Zupee Marks, whether in domain names, social media handles, advertising, or promotional material, is strictly prohibited.</li>
          <li>Users acknowledge and agree that by using the Platform they do not acquire any ownership rights or proprietary interests in the intellectual property of Zupee. No portion of the Platform may be copied, modified, reproduced, republished, uploaded, transmitted, or distributed in any form or by any means, without the prior written consent of Zupee.</li>
          <li>Zupee respects the intellectual property rights of others and expects Users to do the same. If any User or third party believes that their copyright, trademark, or other intellectual property rights have been infringed by any Content or activity on the Platform, they may submit a written complaint with all relevant details to Zupee. Upon verification, Zupee shall take appropriate remedial action, which may include removal of infringing material, suspension of the offending account, or reporting to competent authorities.</li>
          <li>User Content, Rights, and Liabilities: The Platform may allow Users to create, upload, share, or otherwise publish content, including gameplay recordings, text, images, comments, reviews, or other submissions (“User Content”). Users remain the sole owners of their respective User Content; however, by submitting such content on or through the Platform, Users grant Zupee a worldwide, royalty-free, irrevocable, non-exclusive, perpetual, transferable, and sublicensable license to host, use, reproduce, adapt, modify, publish, distribute, publicly perform, and display such content in connection with the operation, promotion, and improvement of the Platform.</li>
          <li>Users represent and warrant that their User Content does not infringe upon the intellectual property rights, privacy rights, or any other legal rights of third parties, and that it does not contain any harmful, unlawful, or inappropriate material. Users shall be solely responsible for their User Content and agree to indemnify and hold Zupee harmless from any claims, damages, liabilities, or expenses arising out of or in connection with such content.</li>
          <li>Zupee reserves the right, but not the obligation, to monitor, review, screen, edit, or remove User Content at its sole discretion, particularly where such content violates these Terms, applicable laws, or community standards, or where it is otherwise harmful to the reputation, security, or interests of Zupee and its Users.</li>
          <li>Further, Users acknowledge and agree that Zupee may be legally required to preserve, disclose, or share User Content with governmental or judicial authorities pursuant to lawful requests, investigations, or legal processes.</li>
          <li>Responsible Content Consumption and Restrictions: The Platform is committed to promoting a safe, responsible, and enjoyable content-viewing experience. The micro-series, short-format shows, and other content made available are for entertainment and informational purposes only. Users are advised not to consider any content as professional advice, financial guidance, medical recommendation, or otherwise actionable information.</li>
          <li>The Platform may host content that is fictional, dramatized, or user-generated, which may not always represent facts. Users acknowledge that interpretation of such content is at their own discretion and that the Platform shall not be liable for any consequences arising from reliance on such content.</li>
          <li>Use of the Platform is restricted to individuals who are eighteen (18) years of age or older. Minors may access the Platform only under the supervision of a parent or legal guardian, who shall be responsible for the minor’s conduct and exposure to content. Certain micro-series may carry age ratings, warnings, or disclaimers and Users are required to adhere to such restrictions.</li>
          <li>To promote healthy viewing habits, the Platform encourages Users to:</li>
          <ul className='list-disc list-inside ml-8 space-y-2 text-sm sm:text-lg'>
            <li>Take regular breaks during content consumption.</li>
            <li>Enable watch-time reminders where available.</li>
            <li>Exercise discretion when viewing sensitive or mature-themed content.</li>
          </ul>
          <li>The Platform reserves the right to restrict, suspend, or terminate access for Users who misuse the service, attempt unauthorized distribution of content, or breach age/content restrictions. The Platform may also implement geo-blocking to restrict access in regions where certain content is prohibited by law.</li>
          <li>Intermediary Status: We act as an intermediary as defined under the Information Technology Act, 2000 and the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021. These Terms are published in accordance with Rule 3(1) of the said Rules, which mandate the publication of the rules, regulations, Privacy Policy, and Terms of Use governing access to and use of the Platform. Our role is limited to providing a digital space where Users may upload, share, and display content created by them or shared by other Users. As an intermediary, we do not exercise editorial control over the content hosted on the Platform, nor are we responsible for the actions or conduct of Users (whether online or offline). We are not liable for third-party services, features, or content that may be accessed through the Platform. Our liability, if any, shall be restricted strictly to the extent provided under applicable Indian law. You acknowledge and agree that we shall not be liable for any loss of profits, revenues, information, data, or for any consequential, special, indirect, exemplary, punitive, or incidental damages arising out of or in connection with these Terms, including but not limited to instances where we remove or delete your content, information, or account. We expect all Users to comply with our Content and Community Guidelines while using the Platform.</li>
          <li>Prohibited Conduct: You agree not to disrupt, interfere with, or attempt to compromise the integrity of the Platform or its services. This includes but is not limited to:</li>
          <ul className='list-disc list-inside ml-8 space-y-2 text-sm sm:text-lg'>
            <li>Accessing or attempting to access non-public areas of the Platform, our Services, or our technical infrastructure.</li>
            <li>Uploading, transmitting, or introducing trojans, viruses, malware, bots, or any other harmful or malicious code.</li>
            <li>Scraping, harvesting, or attempting to collect information from the Platform without authorization.</li>
            <li>Probing, scanning, or testing the vulnerability of any system, network, or security measure deployed by us.</li>
            <li>Tampering with or attempting to tamper with the technological design, architecture, or delivery mechanisms of the Platform.</li>

          </ul>
          <li>Any such conduct shall result in the immediate suspension or termination of your account and may be reported to appropriate law enforcement or regulatory authorities. We also reserve the right to initiate legal proceedings against you for any such unlawful acts.</li>
          <li>Payments, Subscriptions, and Refunds: The Platform may provide both free-to-view content and premium content accessible through subscription plans, pay-per-view charges, or other paid models. Users agree to pay all applicable charges for availing premium features, as per the pricing displayed at the time of subscription. Payments may be processed through authorized payment gateways, including credit/debit cards, wallets, UPI, or other methods enabled on the Platform. Users agree to provide accurate and lawful payment information and authorize the Platform to process charges as per the selected plan. Subscription plans may be offered on monthly, quarterly, or annual terms. Unless cancelled prior to renewal, subscriptions may automatically renew at the prevailing rates. Users are responsible for reviewing applicable pricing and renewal terms before continuing usage. Refunds shall be granted only where required by law or in instances of proven erroneous deductions directly attributable to the Platform. Subscription cancellations will not entitle Users to pro-rata refunds for partially used periods, unless specifically stated otherwise. </li>
          <li>Disclaimers, Warranties, and Limitations of Liability: The Platform and its content are provided on an “as is” and “as available” basis, without warranties of any kind, express or implied. To the fullest extent permitted by law, the Platform disclaims all warranties, including but not limited to fitness for a particular purpose, uninterrupted availability, accuracy, reliability, or completeness of content. While the Platform endeavors to curate high-quality micro-series and related content, it does not guarantee that:</li>
          <ul className='list-disc list-inside ml-8 space-y-2 text-sm sm:text-lg'>
            <li>Content will meet every User’s expectations.</li><li>The Platform will be free from errors, interruptions, viruses, or security vulnerabilities.</li><li>Content displayed is accurate, factual, or suitable for all audiences.</li>
          </ul>
          <li>Users acknowledge that their use of the Platform is at their sole discretion and risk. To the maximum extent permitted under law, the Platform shall not be liable for any indirect, incidental, or consequential damages, including but not limited to loss of data, revenue, goodwill, or emotional distress, arising out of the use of the Platform.</li>
          <li>The Platform is not responsible for:</li>
          <ul className='list-disc list-inside ml-8 space-y-2 text-sm sm:text-lg'>
            <li>Third-party advertisements, links, or integrations displayed on the Platform.</li>
            <li>User-generated content uploaded, shared, or distributed by other Users.</li>
            <li>Interruptions or failures caused by third-party service providers, internet connectivity, or device malfunctions.</li>
          </ul>
        </ul>


        <hr className='mt-10' />

        {/* Section Heading */}
        <h2 className="text-xl sm:text-4xl font-bold italic text-center text-purple-800 mt-10 mb-6">
          J. Prevention of Collusion and Fraud
        </h2>

        {/* Ordered List */}
        <ol className="list-decimal list-inside space-y-3 text-sm sm:text-lg">
          <li>
            We are committed to promoting fair play on our Platform.
          </li>
          <li>

            Our compliance team will track game play of all Users and strict
            action will be taken against any User(s) caught colluding. By
            agreeing to these Terms, you agree not to indulge in any unfair game
            practice that may provide undue advantage to you or any other User.

          </li>
          <li>

            In the event any User is found undertaking such activity on the
            Platform, We shall be entitled, in our sole and absolute discretion,
            to suspend or terminate such User’s account. We reserve the right to
            permanently block the account of the User involved in such activity.
            Any amounts deposited by such User on the Platform shall stand
            forfeited.

          </li>
          <li>

            We reserve the right to withhold any necessary action, as it deems
            fit, against Users found indulging in unfair means. The action could
            include, inter alia, monetary penalties, temporary account
            suspension, redemption blocking and/or permanent account
            deactivation. Any User involved in violation of these Terms is
            liable for prosecution.

          </li>
          <li>

            By using the Platform, including any sub-domains of the Platform, or
            related top-level domains including mobile sites, apps, APIs and
            widgets and/or registering yourself with us, you authorize us or our
            representatives to contact you via email or phone call or SMS
            including third party messaging apps to offer you our services
            including but not limited to impart product knowledge, offer/explain
            any promotional offers running on the Platform and offers offered by
            third parties, for which reasons, personally identifiable information
            may be collected. Irrespective of the fact that you have registered
            yourself under DND or DNC or NCPR service, you still authorize us or
            our representatives to contact you by any means aforementioned for
            the above-mentioned purposes or any other related purpose till the
            time you are registered with us or even after cessation of
            registration.

          </li>
        </ol>

        <hr className='mt-10' />



        {/* Section Heading */}
        <h2 className="text-xl sm:text-4xl font-bold italic text-center mt-10  text-purple-800 mb-6">
          K. Intellectual Property
        </h2>

        {/* Ordered List */}
        <ol className="list-decimal list-inside space-y-3 text-sm sm:text-lg">
          <li>
            The Platform includes a combination of Content created by Us, its
            partners, affiliates, licensors, associates and/or Users. The
            intellectual property rights (Intellectual Property Rights) in all
            software and the Platform and material published on the Platform,
            including (but not limited to) Games, games software, advertisements,
            written Content, photographs, graphics, images, illustrations, marks,
            logos, audio or video clippings and flash animation, is owned by Us,
            its affiliates, partners, licensors and/or associates. Users may not
            modify, publish, transmit, participate in the transfer or sale of,
            reproduce, create derivative works of, distribute, publicly perform,
            publicly display, or in any way exploit any of the materials or
            Content either in whole or in part without express written consent
            from Us. Nothing in these Terms shall be construed to convey and the
            Users by virtue of these Terms shall not acquire any ownership or
            other interest or right in any intellectual property any of the
            materials or content on the Platform.
          </li>
          <li>
            Users may request permission to use any Content by writing into
            helpdesk at support@zupee.com.
          </li>
          <li>
            Users are solely responsible for all materials (whether publicly
            posted or privately transmitted) that they upload, post, e-mail,
            transmit, or otherwise make available on the Platform (Users Content).
            Each User represents and warrants that he/she owns all Intellectual
            Property Rights in the User’s Content and that no part of the User’s
            Content infringes any third-party rights. Users further confirm and
            undertake to not display or use of the names, logos, marks, labels,
            trademarks, copyrights, or intellectual and proprietary rights of any
            third party on the Platform.
          </li>
          <li>
            Users agree to indemnify and hold harmless Us, our directors,
            officers, employees, affiliates and assigns from and against all
            costs, damages, loss and/ or harm including towards litigation costs
            and counsel fees, in respect of any third party claims that may be
            initiated including for infringement of Intellectual Property Rights
            arising out of such display or use of the names, logos, marks, labels,
            trademarks, copyrights or Our intellectual and proprietary rights, by
            such User or through the User’s commissions or omissions. We reserve
            the right to assume the exclusive defence and control of any matter
            otherwise subject to indemnification by you in which event you will
            assist and cooperate with Us in asserting any available defences.
          </li>
          <li>
            Users hereby grant Us and our affiliates, partners, licensors and
            associates a worldwide, irrevocable, perpetual, royalty-free,
            non-exclusive, sub-licensable, license to use, store, reproduce,
            create derivative works of, distribute, publicly perform, publicly
            display, transfer, transmit, and/or publish Users’ Content for any of
            the following purposes:
            <ol className="list-[lower-alpha] list-inside ml-6 space-y-2">
              <li>displaying Users’ Content on Platform;</li>
              <li>
                distributing Users’ Content, either electronically or via other
                media, to other Users seeking to download or otherwise acquire it;
                and/or
              </li>
              <li>
                storing Users’ Content in a remote database accessible by end
                Users, for a charge.
              </li>
            </ol>
          </li>
          <li>
            This license shall apply to the distribution and the storage of Users’
            Content in any form, medium, or technology.
          </li>
          <li>
            The license shall not lapse due to non-use by Us under any provision
            of law.
          </li>
          <li>
            All names, logos, marks, labels, trademarks, copyrights or
            intellectual and proprietary rights on the Platform belonging to any
            person (including User), entity or third party are recognized as
            proprietary to the respective owners and any claims, controversy or
            issues against these names, logos, marks, labels, trademarks,
            copyrights or intellectual and proprietary rights must be directly
            addressed to the respective parties under notice to Us.
          </li>
        </ol>

        <hr className='mt-10' />
        {/* Heading */}
        <h2 className="mt-10 text-xl sm:text-xl text-center md:text-4xl text-purple-800  font-bold italic mb-4">
          L. Testimonial Terms
        </h2>

        {/* Content */}
        <ol className="list-decimal list-inside space-y-4 text-gray-700 text-sm sm:text-lg leading-relaxed">
          <li>
            We may capture and obtain visual and/or audio recordings or
            performances, still images of the User, and text provided by the User
            for the testimonial being provided towards the Platform (the results
            of which are the Recordings). The Recordings provided by the User are
            voluntary and We are the sole and exclusive owner of all rights in and
            to the Recordings, and all elements thereof (including, without
            limitation, the copyright thereto). Without prejudice to the above,
            the User grants to Us a perpetual royalty-free license, to publicly
            use, distribute, reproduce, create derivative works from, and
            perform/display the user’s name, voice, likeness, appearance,
            biographical information, and other indicia of its identity as
            included in the Recordings and any excerpts or version thereof for
            their marketing, in any language, and without any geographical
            limitation. We may incorporate the recordings and any separate content
            (e.g., quotes, photos, videos, artwork, materials, etc.) to market
            their Platform and Services. The User also hereby waives any right to
            inspect or approve the finished matter based on the Recording that may
            be used now or in the future, whether that use is known to the user or
            unknown.
          </li>

          <li>
            We are not obligated to use the Recordings if it so wishes. The User
            will not attempt to enjoin or otherwise impair Our use of the
            Recordings that is in accordance with this Release.
          </li>
        </ol>

        <hr className='mt-10' />


        {/* Heading */}
        <h2 className="text-xl sm:text-2xl md:text-4xl font-bold italic mt-10 text-purple-800 text-center mb-4">
          M. In app purchases and payments
        </h2>

        {/* Content */}
        <ol className="list-decimal list-inside space-y-4 text-gray-700 text-sm sm:text-lg leading-relaxed">
          <li>
            There may be certain services for which you are required to make
            payments, such as purchasing Virtual Currency, Virtual Goods, tokens,
            tickets and upgrades. To participate in these services, you must have
            a valid Account. You are responsible for all charges and activities on
            your Account, including any applicable taxes, as well as any purchases
            made by you or anyone using your Account.
          </li>

          <li>
            It is your responsibility to provide accurate and up-to-date
            information. You must promptly update any changes, such as billing
            address, payment information, or expiration date. Customers using
            certain payment methods may be subject to additional payment
            processing fees.
          </li>

          <li>
            In-app purchases are non-refundable. We maintain a strict no-refund
            policy for all in-app purchases.
          </li>
        </ol>












        <hr className='mt-10' />

        {/* Heading */}
        <h2 className="text-xl sm:text-2xl md:text-4xl font-bold italic mt-10 text-purple-800 text-center mb-4">
          N. ADVERTISING
        </h2>

        {/* Ordered List */}
        <ol className="list-decimal list-inside space-y-4 text-gray-700 text-sm sm:text-lg leading-relaxed">
          <li>
            We reserve the right to use and disclose the collected, non-personal
            data for purposes of advertising by us or our partners and
            contractors. We may employ third parties for ad serving technologies
            who may use certain methods to collect information as a result of ad
            serving through services.
          </li>

          <li>
            We and these entities may use various identifiers to collect
            information about your use of the App, including but not limited to
            your IP address, MAC address, device identifiers, software and
            hardware information, time zone and usage information. This
            information may be used by us and others to, among other things,
            determine the popularity of certain content, deliver contextual
            advertising, and content and better understand your activity on the
            Apps.
          </li>

          <li>
            Third-party ad serving technologies are integrated into the App, so if
            you do not want to be subject to these technologies, please do not use
            or access the Apps.
          </li>

          <li>
            Users acknowledge and agree that the other brand ambassadors are
            merely endorsing the Platform, and will not be liable for any claims,
            damages, or disputes arising from use of the Platform and Services.
          </li>
        </ol>

        <hr className='mt-10' />


        {/* Heading */}
        <h2 className="text-xl sm:text-2xl md:text-4xl font-bold italic mt-10 text-purple-800 text-center mb-4">
          O. Third Party Sites, Services and Products
        </h2>

        {/* Ordered List */}
        <ol className="list-decimal list-inside space-y-4 text-gray-700 text-sm sm:text-lg leading-relaxed">
          <li>
            The Platform may contain links to other Internet sites owned and
            operated by third parties. Users’ use of each of those sites is
            subject to the conditions, if any, posted by such third-party sites.
            We do not exercise control over any Internet sites apart from Us and
            cannot be held responsible for any content residing in any third-party
            Internet site. Our inclusion of third-party Content or links to
            third-party Internet sites is not an endorsement by Us of such
            third-party Internet site.
          </li>

          <li>
            Users’ correspondence, transactions/offers or related activities with
            third parties, including payment providers and verification service
            providers, are solely between the User and that third party. Users’
            correspondence, transactions, and usage of the services/offers of such
            third party shall be subject to the terms and conditions, policies and
            other service terms adopted/implemented by such third party, and the
            User shall be solely responsible for reviewing the same prior to
            transacting or availing of the services/offers of such third party.
            User agrees that We will not be responsible or liable for any loss or
            damage of any sort incurred as a result of any such
            transactions/offers with third parties. Any questions, complaints, or
            claims related to any third-party product or service should be
            directed to the appropriate vendor.
          </li>

          <li>
            The Platform contains Content that is created by Us as well as content
            provided by third parties. We do not warranty the accuracy, integrity,
            quality of the content provided by third parties and such content may
            not be relied upon by the Users in utilizing the Services provided on
            the Platform including while participating in any of the Games hosted
            on the Platform.
          </li>
        </ol>


        <hr className='mt-10' />
        {/* Heading */}
        <h2 className="text-xl sm:text-2xl md:text-4xl font-bold italic mt-10 text-purple-800 text-center mb-4">
          P. Privacy
        </h2>

        {/* Ordered List */}
        <ol className="list-decimal list-inside space-y-4 text-gray-700 text-sm sm:text-lg leading-relaxed">
          <li>
            By using the Platform and providing any of your personal information
            to the Platform, You affirmatively consent and agree to comply with
            our Privacy Policy (link given above), guidelines and statements as
            may be applicable from time to time, which are incorporated into and
            forms an integral part of these Terms. If you do not agree to the
            terms of the Privacy Policy in its entirety or have objections to the
            use of your information, you may not access or otherwise use the
            Platform or its Services.
          </li>
        </ol>
        <hr className='mt-10' />
        {/* Heading */}
        <h2 className="text-xl sm:text-2xl md:text-4xl font-bold italic mt-10 text-purple-800 text-center mb-4">
          Q. Disconnection and Technical Issues
        </h2>

        {/* Ordered List */}
        <ol className="list-decimal list-inside space-y-4 text-gray-700 text-sm sm:text-lg leading-relaxed">
          <li>
            You understand and acknowledge that once a game has commenced, not
            being able to play due to slow internet connections, faulty hardware,
            technical failure due to customer’s hardware, internet connection
            failure, low computer configuration or for any other reason not
            attributable to us does not require us to issue a refund of the
            participation amount you may have paid for participation.
          </li>

          <li>
            In case of any technical failures, server crashes, breakdowns, software
            defects, disruption or malfunction of service at our end, as a policy,
            we will cancel the Game(s) and refund the participation amounts after
            proper verification and no service fee will be charged for such Games
            and you accept that we are not responsible to you in all such cases.
            For any game, we have the right to cancel and refund the participation
            amount. In no case, other than a server crash, are we accountable for
            any of the User’s disconnections from the server. We are also not
            liable for any prospective Winnings from any incomplete game.
          </li>

          <li>
            We do not hold any liability to any disconnection, lag, freeze or
            interference in the network on the User’s computer or any other
            external networks.
          </li>

          <li>
            Zupee assumes no responsibility for any technical issues, including
            errors, omissions, interruptions, deletions, defects, delays, or
            damages in the operation of the Platform or participation in the
            Scheme. The Company also accepts no liability for late, lost,
            incomplete, incorrect, or misdirected entries, or any issues such as
            loss of SMS, internet connectivity, unique codes, documents, drafts,
            claims, or correspondence, whether caused by error, tampering,
            hacking, deletion, theft, virus attacks, transmission interruptions,
            or hardware failure.
          </li>
        </ol>
        <hr className='mt-10' />
        {/* Heading */}
        <h2 className="text-xl sm:text-2xl md:text-4xl font-bold italic mt-10 text-purple-800 text-center mb-4">
          R. Enforceability
        </h2>

        {/* Ordered List */}
        <ol className="list-decimal list-inside space-y-4 text-gray-700 text-sm sm:text-lg leading-relaxed">
          <li>
            By registering, you are considered to have accepted and understood all
            the Terms herein and the relevant Game specific rules and regulations.
            We recommend that you keep a copy of all transactions, gaming rules,
            cancellation, and payment policies. Our failure or delay to act or
            exercise any right or remedy with respect to a breach of any of these
            Terms by you does not amount to surrendering or waiving our rights to
            act with respect to any prior, concurrent, subsequent, or similar
            breaches.
          </li>

          <li>
            If any judicial or quasi-judicial body declares any of the provisions
            of these Terms to be unlawful, invalid, void, or unenforceable for any
            reason, the validity and enforceability of the remaining provisions
            will not be affected. Any such inappropriate term or condition will be
            replaced with another term or condition that is valid and enforceable
            and most closely reflects the intent and effect of the original
            invalid term. In such an event, the parties shall be obligated to
            construe and interpret the void, illegal or unenforceable provision
            with a valid, legal, and enforceable provision in such manner that
            corresponds as closely as possible to Our intent and objective in the
            void, illegal or unenforceable provisions.
          </li>
        </ol>
        <hr className='mt-10' />
        {/* Heading */}
        <h2 className="text-xl sm:text-2xl md:text-4xl font-bold italic mt-10 text-purple-800 text-center mb-4">
          S. Disclaimer of Warranties
        </h2>

        {/* Ordered List */}
        <ol className="list-decimal list-inside space-y-4 text-gray-700 text-sm sm:text-lg leading-relaxed">
          <li>
            We disclaim any and all warranties, expressed or implied, in
            connection with the underlying software of the Platform, the Website
            and the Game(s), all of which are provided to the User as is.
          </li>
          <li>
            You agree that use of the Services and the access to the Platform is
            at Your own risk. The Services including the Platform, the Content,
            the Games, and any other materials contained on or provided through
            the Platform are provided “AS IS” and, to the fullest extent permitted
            by law, are provided without warranties of any kind, either express or
            implied. Without limiting the foregoing, We do not make any warranties
            of fitness for a particular purpose, title, merchantability,
            completeness, availability, security, compatibility, or
            non-infringement; or that the Services will be uninterrupted, free of
            viruses, malware, or other harmful components, accurate, error free or
            reliable.
          </li>
          <li>No person affiliated or claiming affiliation with the Platform has authority to extend such warranties.</li>
          <li>
            Without limiting the generality of the foregoing, to the maximum
            extent permitted by applicable law, we shall have no liability for any
            damages or injury caused, in whole or in part, by contingencies or
            issues beyond our reasonable control, including, but not limited to:
            the acts of third parties, errors in the Content or the Platform,
            network failures, internet failures, software and hardware failures,
            viruses and other system attacks, labour stoppages, riots, acts of
            government or god, natural disasters, acts of terrorism, communication
            line failure, or theft, destruction of, unauthorized access to,
            alteration of or use of records.
          </li>
          <li>
            To the maximum extent permitted by applicable law, you hereby agree
            that you shall have no remedy in respect of any statement,
            representation, assurance, or warranty (whether made innocently or
            negligently) that is not set out in these Terms. You agree that you
            shall have no claim for innocent or negligent misrepresentation or
            negligent misstatement based on any statement in these Terms.
          </li>
          <li>
            The foregoing limitations shall apply regardless of whether (i)
            liability or damage is alleged for breach of contract, tortious
            behaviour, negligence, or under any other theory or cause of action,
            and/or (ii) the party against which liability or damages is sought was
            advised of the possibility thereof. For the avoidance of doubt,
            nothing in these Terms shall limit or exclude liability for (i) death
            or personal injury caused by negligence; or (ii) fraud.
          </li>
          <li>
            To the maximum extent permitted by applicable law, you agree that
            regardless of any statute or law to the contrary, any claim or cause
            of action arising out of or related to these Terms, the Platform, or
            any part thereof, must be asserted within one (1) year after such
            claim or cause of action arose, or it shall be forever barred.
          </li>
          <li>
            You agree and acknowledge that We do not promise or ensure that you
            will be able to access your Account whenever you want. It is entirely
            possible that you may not be able to access your Account, or the
            Platform provided by Us at times or for extended periods of time due
            to, but not limited to system maintenance and updates.
          </li>
          <li>We make no guarantees, warranties, representations, or other promises relating to the game(s).</li>
          <li>
            You will be solely responsible for any delay and/or damage to your
            computer systems or loss of data that results from the installation of
            any software on your computer, and we expressly disclaim liability for
            any such failure and/or delay.
          </li>
          <li>
            You agree to assume the entire risk as to the results and performance
            of any software and/or Game(s) availed by you on the Platform. As
            such, the result and performance among other things depends on your
            internet connection and hardware. You also assume the entire cost of
            all servicing, repair and/or correction of your hardware when you
            access, download, or execute software or Game(s) available on the
            Platform. We explicitly disclaim liability for any delay or failure to
            perform resulting from installation of any software on your computer.
          </li>
          <li>
            You specifically acknowledge, agree and accept that we are not liable
            to you for: (i) the defamatory, offensive or illegal conduct of any
            other User or for anything that turns out to be misleading,
            inaccurate, defamatory, threatening, obscene or otherwise illegal
            whether originating from another User or otherwise; (ii) any loss
            whatsoever arising from the use, abuse or misuse of your Account on
            our Platform; (iii) any loss incurred in transmitting information from
            you to our Platform by the Internet or by other connecting media; (iv)
            any technical failures, system breakdowns, defects, delays,
            interruptions, manipulated or improper data transmission, loss or
            corruption of data or communications’ lines failure, distributed
            denial of service attacks, viruses or any other adverse technological
            occurrences arising in connection with your access to or use of our
            Platform; (v) the accuracy, completeness or currency of any
            information services provided or any statistics shown on the Platform.
          </li>
          <li>
            Company shall not be liable to perform any of its/their respective
            obligations under the Contest or in respect of the prize where it is
            unable to do so as a result of circumstances beyond its/their control
            in the nature of fire, explosions, natural calamities, state
            emergency, riots, change in law, order or decree of any governmental
            or regulatory authority, or any other force majeure condition, etc.,
            and shall not be liable to compensate the User in these circumstances.
          </li>
        </ol>
        <hr className='mt-10' />
        {/* Heading */}
        <h2 className="text-xl sm:text-2xl md:text-4xl font-bold italic mt-10 text-purple-800 text-center mb-4">
          T. Indemnification and Limitation of Liability
        </h2>

        {/* Ordered List */}
        <ol className="list-decimal list-inside space-y-4 text-gray-700 text-sm sm:text-lg leading-relaxed">
          <li>
            You clearly understand and agree that We shall under no circumstances
            (including, without limitation, in contract, negligence or other
            tort), be liable for any direct, indirect, ancillary, special,
            incidental, consequential, or exemplary or punitive damages. This
            includes, but is not limited to injury, claim, loss of data, loss of
            income, loss of profit or loss of opportunity, loss of or damage to
            property, damages for monetary loss, goodwill, use, data or other
            intangible loss (even if We have been advised of the possibility of
            such damages), resulting from or arising out of the use of or the
            inability to use the Platform, even if we have been advised or become
            aware of the possibility of such damages or loss or that such loss was
            foreseeable.
          </li>

          <li>
            You agree to indemnify us and each of our respective general and
            limited partners, Users, shareholders, directors, officers, employees,
            agents, representatives, vendors and business partners harmless from
            and against any and all claims, liabilities, obligations, losses,
            costs or debt, damages and expenses (including attorneys’ fees and
            court costs) arising out of or relating to:
            <ol className="list-[lower-alpha] list-inside space-y-2 mt-2 ml-4">
              <li>
                breach of these Terms, in tort (including negligence) third party
                claims or liabilities arising against Us out of such a breach,
                based in contract, tort, statute, fraud, misrepresentation, or any
                other legal theory, and regardless of whether a claim arises
                during or after the termination of these Terms;
              </li>
              <li>
                your use of the Platform in any matter that is contrary to
                applicable laws, with an intent to deceive, defraud cheat,
                mislead, or solicit any business, monetary or non-monetary
                consideration or information from another User;
              </li>
              <li>
                your breach of any applicable laws or governmental or judicial
                order which applies to your use of the Platform from a specific
                geography;
              </li>
              <li>
                your use of the Platform, including but not limited to your
                posting, use of, modification or interaction with any content on
                the Platform;
              </li>
              <li>
                any unauthorized, improper, illegal, or wrongful use of your
                Account by any person, including a third party, whether or not
                authorized or permitted by you;
              </li>
              <li>your User Content;</li>
              <li>
                use by any other person accessing the Platform using your username
                or password, whether or not with your authorization;
              </li>
              <li>
                the use by us of information provided by you through our Platform.
              </li>
            </ol>
          </li>

          <li>
            This indemnification obligation will survive the expiry or termination
            of these Terms and your use of the Platform.
          </li>

          <li>
            There could be instances where We are not able to receive prompt
            updates about the change in applicable laws of your place of stay. It
            is your obligation to ensure that any activities you engage on the
            Platform are legal as per the applicable laws. You agree to indemnify
            and hold harmless, We or the Platform, from any claim, demand, damage,
            or loss whatsoever coming out due to your non-compliance with the laws
            of your jurisdiction.
          </li>
        </ol>
        <hr className='mt-10' />
        {/* Heading */}
        <h2 className="text-xl sm:text-2xl md:text-4xl font-bold italic mt-10 text-purple-800 text-center mb-4">
          U. Termination
        </h2>

        {/* Ordered List */}
        <ol className="list-decimal list-inside space-y-4 text-gray-700 text-sm sm:text-lg leading-relaxed">
          <li>
            We may change, suspend, or discontinue any aspect of the Platform at
            any time, including the availability of any Platform’s feature,
            database, or Content. We may also impose limits on certain features
            and services or restrict your access to parts or the Platform, without
            notice or liability at any time in our exclusive discretion, without
            prejudice to any legal or equitable remedies available to us, for any
            reason or purpose. However, under normal circumstances, we will only
            do so where there has been conduct that we believe violates these
            Terms or other rules and regulations or guidelines posted on the
            Platform or conduct which we believe is harmful to other Users, to our
            businesses, or other information providers.
          </li>

          <li>
            Upon any termination of these Terms, you shall immediately discontinue
            your use and access to the Platform and destroy all materials obtained
            from it. You hereby agree and consent to the above and agree and
            acknowledge that we can, at our sole discretion, exercise our right in
            relation to any or all of the above, and that we shall not be liable
            in any manner of the same; and you agree, acknowledge and consent to
            the same.
          </li>

          <li>
            You acknowledge that your representations, undertakings, and
            warranties and the clauses relating to indemnities, limitation of
            liability, grant of license, governing law and jurisdiction,
            confidentiality shall survive the efflux of time and the termination
            of these Terms.
          </li>
        </ol>
        <hr className='mt-10' />
        {/* Heading */}
        <h2 className="text-xl sm:text-2xl md:text-4xl font-bold italic mt-10 text-purple-800 text-center mb-4">
          V. Publicity
        </h2>

        {/* Ordered List */}
        <ol className="list-decimal list-inside space-y-4 text-gray-700 text-sm sm:text-lg leading-relaxed">
          <li>
            Acceptance of prize(s) by the winner, constitutes permission for
            Company and its affiliates to use the winner’s name, likeness, image,
            voice, photo, audio-visual, videos, recordings, audio tapes, digital
            images and the like for advertising and promotional purposes in any
            media worldwide for purposes of advertising and trade without any
            further permissions or consents and/or additional compensation
            whatsoever. The winners further undertake that they will be available
            for promotional purposes as planned and desired by the Company without
            any charge. Promotional activities may include but not be limited to
            press events, internal meetings, social media, and
            ceremonies/functions.
          </li>
        </ol>
        <hr className='mt-10' />
        {/* Heading */}
        <h2 className="text-xl sm:text-2xl md:text-4xl font-bold italic mt-10 text-purple-800 text-center mb-4">
          W. Dispute Resolution
        </h2>

        {/* Ordered List */}
        <ol className="list-decimal list-inside space-y-4 text-gray-700 text-sm sm:text-lg leading-relaxed">
          <li>
            In case you have any grievances with respect to the Platform or the Services, you can send an email to us <a href="mailto:support@zupee.com" className="text-purple-700 underline">support@zupee.com</a>. Subject to the clauses below, the courts of competent jurisdiction at Haryana shall have exclusive jurisdiction to determine any and all disputes arising out of, or in connection with the Platform provided by Us (including the games, construction, validity, interpretation and enforceability of these Terms, or the rights and obligations of the Users), as well as the exclusive jurisdiction to grant interim or preliminary relief in case of any dispute referred to arbitration as given below. All such issues and questions shall be governed and construed in accordance with the laws of India.
          </li>

          <li>
            In the event of any legal dispute (which may be a legal issue or question) which may arise, the party raising the dispute shall provide a written notification (Notification) to the other party. On receipt of Notification, the parties shall first try to resolve the dispute through discussions. In the event that the parties are unable to resolve the dispute within fifteen (15) days of receipt of Notification, the dispute shall be settled by arbitration.
          </li>

          <li>
            The seat and venue of arbitration shall be New Delhi, India. All arbitration proceedings shall be conducted in English and in accordance with the provisions of the Arbitration and Conciliation Act, 1996, as amended from time to time. The parties shall mutually appoint a sole arbitrator.
          </li>

          <li>
            The arbitration award will be final and binding on the parties, and each party will bear its own costs of arbitration and equally share the fees of the arbitrator unless the arbitral tribunal decides otherwise.
          </li>

          <li>
            The arbitrator shall be entitled to pass interim orders and awards, including the orders for specific performance and such orders would be enforceable in competent courts of Gurgaon. The arbitrator shall give a reasoned award.
          </li>

          <li>
            Nothing contained in these Terms shall prevent Us from seeking and obtaining interim or permanent equitable or injunctive relief, or any other relief available to safeguard its interest prior to, during or following the filing of arbitration proceedings or pending the execution of a decision or award in connection with any arbitration proceedings from any courts of competent jurisdiction at Haryana to grant the same. The pursuit of equitable or injunctive relief shall not constitute a waiver on the part of Us to pursue any remedy for monetary damages through the arbitration described herein.
          </li>

          <li>
            <strong>Caution:</strong> Any attempt to deliberately damage the Company's Platform or the information on the Platform, to cause malicious damage or interference with the normal functioning of the Platform, or to otherwise undermine the legitimate operation of any Contest may be a violation of criminal and civil laws and should such an attempt be made, whether successful or not, the Company reserves the right to seek damages to the fullest extent permitted by law. If the Company suffers loss or incurs any costs in connection with any breach of these Terms or any other legal obligation by a User, the User agrees to indemnify the Company for those losses, damages, and costs.
          </li>
        </ol>
      </div >

    </>
  )
}

export default TandC